# coding=utf-8
import os.path

# Web stuff
import tornado
import tornado.options
import bokeh
from bokeh.server.server import Server
from bokeh.util.browser import view

# Local handlers
from handlers.handlers import MainHandler, LoginHandler, bokeh_app, SecondHandler
#from handlers.handlers import MainHandler, LoginHandler, SecondHandler

# Parametrize tornado
tornado.options.define("port",
                       default=8888,
                       help="run on the given port",
                       type=int)


class Application(tornado.web.Application):
    def __init__(self):
        handlers = [
            (r"/", MainHandler),
            (r"/main_page", MainHandler),
            (r"/second_page",SecondHandler),
            (r"/login", LoginHandler),
        ]
        settings = dict(
                template_path=os.path.join(os.path.dirname(__file__), "templates"),
                static_path=os.path.join(os.path.dirname(__file__), "static"),
                xsrf_cookies=True,
                # NOTE: some random value as secret (i.e. generated by uuid4())
                cookie_secret="YOUR SECRET HERE",
                login_url="/login", # redirect() will go there
                debug=True,
        )
        super(Application, self).__init__(handlers, **settings)



if __name__ == '__main__':
    # First instantiate main tornado infrastructure
    http_server = tornado.httpserver.HTTPServer(Application())
    http_server.listen(tornado.options.options.port)
    io_loop = tornado.ioloop.IOLoop.current()

    # Now instantiate bokeh app
    bokeh_server = Server({'/bokeh_app': bokeh_app},
                          io_loop=io_loop,
                          allow_websocket_origin=['localhost:8888'])
    #bokeh_server.start()

    # Launch the whole thing
    #io_loop.add_callback(view, "http://localhost:8888/main_page")
    io_loop.start()
